### PR TITLE
Enable basic GitHub Actions CI

### PR DESCRIPTION
**Pull request by friederbluemle**
A very basic CI integration - At the moment only installing dependencies and building the Android code.

We should eventually expand this to also include iOS, tests, linting etc. For now,  these minimal CI steps should never fail.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Unfortunately, this is not ready to merge yet.
It's failing with

```
> Task :moviesreloaded:mergeExtDexRelease
D8: Program type already present: com.ern.api.impl.EnNavigationApiController

com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> Task :moviesreloaded:mergeDexRelease
Program type already present: com.ern.api.impl.EnNavigationApiController
```

https://github.com/friederbluemle/ernnavigation-api-impl-native/runs/418514197

**Comment by deepueg** [comment]
This is because the container is not excluding the `navigation-impl` code. When we run local container we generate the container by excluding the `impl` code using the dev version of the platform.

**Comment by friederbluemle** [comment]
Yeah, thanks for the reply and clarification @deepueg

Since we don't have a clear plan on how it will take for this functionality to become available in a release, I'll take out the `build` step for now. That means we'll run with **very** limited CI. But limited CI is better than no CI, and at least we will be able to set up branch protection/PR head branch up-to-date checks.

**Comment by friederbluemle** [comment]
Build is green:
https://github.com/friederbluemle/ernnavigation-api-impl-native/actions/runs/33536236

🎉

**Pull request merged**
