### PR TITLE
Allow iOS navigation bar icons to fallback on named image assets

### PR DESCRIPTION
**Pull request by ryanliljestrom**
This fixes https://github.com/electrode-io/ernnavigation-api-impl-native/issues/91

### CODE REVIEW

**Comment by ryanliljestrom** [comment]
We submitted a corporate CLA to opensource@walmartlabs.com on Jan 30th, since we are interested in contributing to multiple electrode-native repositories. Is that the correct approach for a corporate CLA, or would we need one for each repo?

**Comment by friederbluemle** [comment]
@ryanliljestrom or @jasonmachata - Can you please rebase your branch?

**Comment by ryanliljestrom** [comment]
@friederbluemle Should be rebased now

**Comment by deepueg** [comment]
@ryanliljestrom thanks for your PR. A new version(`v1.3.22`) of the library is published.

**Pull request merged**
